version: "3"

services:
  api:
    container_name: api
    image: 04-apollo-federation-api
    build:
      context: ./
      dockerfile: ./packages/api/Dockerfile.dev
    ports:
      - 5000:5000
      - 15000:9229
    environment:
      PORT: 5000
      API_NAME: API
      API_ACCOUNTS: http://accounts:5001/graphql
      API_PRODUCTS: http://products:5002/graphql
      API_REVIEWS: http://reviews:5003/graphql
      WAIT_HOSTS: accounts:5001, products:5002, reviews:5003
    volumes:
      - ./packages/api:/usr/src/app/packages/api
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - 04-apollo-federation-network
    restart: unless-stopped

  accounts:
    container_name: accounts
    image: 04-apollo-federation-accounts
    build:
      context: ./
      dockerfile: ./packages/accounts/Dockerfile.dev
    ports:
      - 5001:5001
      - 15001:9229
    environment:
      PORT: 5001
      API_NAME: API-ACCOUNTS
    volumes:
      - ./packages/accounts:/usr/src/app/packages/accounts
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - 04-apollo-federation-network
    restart: unless-stopped

  products:
    container_name: products
    image: 04-apollo-federation-products
    build:
      context: ./
      dockerfile: ./packages/products/Dockerfile.dev
    ports:
      - 5002:5002
      - 15002:9229
    environment:
      PORT: 5002
      API_NAME: API-PRODUCTS
    volumes:
      - ./packages/products:/usr/src/app/packages/products
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - 04-apollo-federation-network
    restart: unless-stopped

  reviews:
    container_name: reviews
    image: 04-apollo-federation-reviews
    build:
      context: ./
      dockerfile: ./packages/reviews/Dockerfile.dev
    ports:
      - 5003:5003
      - 15003:9229
    environment:
      PORT: 5003
      API_NAME: API-REVIEWS
    volumes:
      - ./packages/reviews:/usr/src/app/packages/reviews
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - 04-apollo-federation-network
    restart: unless-stopped

networks:
  04-apollo-federation-network:
    driver: bridge
