version: "3"

services:
  api:
    container_name: 02-node-mongoose
    image: 02-node-mongoose
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:3000
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://02-node-mongoose-db:27017/helloworld
    networks:
      - 02-node-mongoose-network
    depends_on:
      - db

  db:
    container_name: 02-node-mongoose-db
    image: mongo:latest
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 28017:27017
      - 28018:27018
    networks:
      - 02-node-mongoose-network

networks:
  02-node-mongoose-network:
    driver: bridge
